### ISSUE TITLE
Question regarding en locale

### ISSUE THREAD

**Issue by mkarnicki** [coding-socks/lost-in-translation#2]
Hi,

Got two questions for you. I was checking out your package and noticed:
1. There is no license. Have you considered MIT by any chance?
2. Passing 'en' returns the following error:

```
Locale `en` must be different from `en`.
```

I was hoping to verify if the English translation files are missing translation keys used anywhere in Blade templates. Is your package suitable for this purpose?

Thanks a lot and thank you very much for sharing your code!

**Comment by nerg4l** [comment]
Hi,

The project released with MIT license. There is a license file here: https://github.com/coding-socks/lost-in-translation/blob/main/LICENSE

Regarding your second. I originally blocked finding base language translations because I mainly use [translation strings](https://laravel.com/docs/11.x/localization#using-translation-strings-as-keys) and with that the base translation is already there. I guess in your case [short keys](https://laravel.com/docs/11.x/localization#using-short-keys) are used where it is quite a useful feature.

I just pushed v0.3.3 which should allow using it with the base locale.
